"""CLI-first operations for recording and querying notes."""

import json
import os
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import Any

from braindump.config import get_config, get_timezone
from braindump.database import get_db, init_db
from braindump.frontmatter import build_creation_frontmatter, render_frontmatter


_TAG_RE = re.compile(r"(?:^|\s)#([a-zA-Z\u4e00-\u9fff][\w/\u4e00-\u9fff]*)")
_FTS_SPECIAL = re.compile(r'["\*\(\)\-\^]')


def emit(data: dict[str, Any], json_mode: bool, human_lines: list[str] | None = None) -> None:
    """Print a CLI result in human or JSON form."""
    if json_mode:
        print(json.dumps(data, ensure_ascii=False, indent=2))
        return
    for line in human_lines or []:
        print(line)


def _reset_config_for_data_dir(data_dir: Path) -> None:
    """Point config loading at a data dir for the current process."""
    os.environ["BRAINDUMP_DATA_DIR"] = str(data_dir)
    import braindump.config as config_mod

    config_mod._config = None


def _toml_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _default_config_text(data_dir: Path) -> str:
    return f"""# Generated by `braindump init`.

[general]
data_dir = {_toml_string(str(data_dir))}
timezone = "Asia/Shanghai"
day_boundary_hour = 4

[telegram]
api_id = 0
api_hash = ""
bot_token = ""
allowed_users = []

[transcribe]
engine = "whisper"
whisper_model = "small"
whisper_device = "cpu"

[web]
host = "127.0.0.1"
port = 8080
# secret_key = ""

[review]
enabled = false
count = 3
schedule = "09:00"
min_age_days = 7
min_content_length = 20
chat_id = 0

[llm]
enabled = false
base_url = "https://api.moonshot.cn/v1"
model = "kimi-k2.5"
api_key_env = "MOONSHOT_API_KEY"
timeout = 30
min_content_length = 30
"""


def _extract_tags(text: str) -> list[str]:
    return list(dict.fromkeys(_TAG_RE.findall(text)))


def _merge_tags(content: str, explicit_tags: list[str], comma_tags: str = "") -> list[str]:
    tags: list[str] = []
    tags.extend(_extract_tags(content))
    tags.extend(t.strip() for t in comma_tags.split(",") if t.strip())
    tags.extend(t.strip() for t in explicit_tags if t.strip())
    return list(dict.fromkeys(tags))


def _sanitize_fts_query(q: str) -> str:
    q = _FTS_SPECIAL.sub(" ", q.strip())
    tokens = q.split()
    return " ".join(f'"{t}"' for t in tokens if t)


def _split_tags(tags: str | None) -> list[str]:
    return [t.strip() for t in (tags or "").split(",") if t.strip()]


def _preview(text: str | None, max_len: int = 120) -> str:
    value = " ".join((text or "").split())
    if len(value) <= max_len:
        return value
    return value[: max_len - 3] + "..."


def _note_summary(note: dict[str, Any]) -> dict[str, Any]:
    body = note.get("content") or note.get("transcript") or ""
    return {
        "id": note["id"],
        "created_at": note["created_at"],
        "display_date": note["display_date"],
        "type": note["media_type"],
        "source": note["source"],
        "title": note.get("ai_title") or _preview(body, 48),
        "summary": note.get("ai_summary"),
        "mood": note.get("ai_mood"),
        "tags": _split_tags(note.get("tags")),
        "preview": _preview(body),
        "file_path": note.get("file_path"),
    }


async def init_project(data_dir: Path | None, force: bool = False) -> dict[str, Any]:
    """Initialize the braindump data directory, config, and database."""
    target_dir = Path(data_dir).expanduser().resolve() if data_dir else (
        Path(os.environ.get("BRAINDUMP_DATA_DIR", "~/braindump-data")).expanduser().resolve()
    )
    target_dir.mkdir(parents=True, exist_ok=True)
    _reset_config_for_data_dir(target_dir)

    config_path = target_dir / "config.toml"
    created_config = False
    if force or not config_path.exists():
        config_path.write_text(_default_config_text(target_dir), encoding="utf-8")
        created_config = True

    cfg = get_config()
    cfg.ensure_dirs()
    await init_db()

    return {
        "ok": True,
        "data_dir": str(cfg.data_dir),
        "config_path": str(config_path),
        "db_path": str(cfg.db_path),
        "created_config": created_config,
        "next": [
            "Use `braindump add \"text\" --json` to record from CLI.",
            "Edit config.toml when Telegram Bot, LLM summaries, or daily review are needed.",
            "Use `braindump serve` after configuring Telegram credentials.",
        ],
    }


async def add_text_note(content: str, explicit_tags: list[str], comma_tags: str = "") -> dict[str, Any]:
    """Create a text note from CLI input."""
    content = content.rstrip("\n")
    if not content.strip():
        raise ValueError("note content is empty")

    cfg = get_config()
    cfg.ensure_dirs()
    await init_db()

    tz = get_timezone()
    now = datetime.now(tz)
    from braindump.database import _compute_display_date

    display_date = _compute_display_date(now, cfg.general.day_boundary_hour)
    year, month, day = display_date.split("-")
    date_dir = cfg.media_dir / "text" / year / month / day
    date_dir.mkdir(parents=True, exist_ok=True)

    random_hex = os.urandom(4).hex()
    source_id = f"cli{random_hex}"
    filename = f"{now.strftime('%Y%m%d_%H%M%S')}_{source_id}.md"
    filepath = date_dir / filename

    tags = _merge_tags(content, explicit_tags, comma_tags)
    fm = build_creation_frontmatter(
        created_at=now.isoformat(),
        source="cli",
        media_type="text",
        tags=tags,
    )
    filepath.write_text(render_frontmatter(fm, content), encoding="utf-8")
    rel_path = str(filepath.relative_to(cfg.data_dir))

    summarize_status = "pending" if len(content) >= cfg.llm.min_content_length else "skipped"
    tags_storage = ",".join(tags)

    db = await get_db()
    try:
        cursor = await db.execute(
            """INSERT INTO notes
               (content, media_type, file_path, file_size,
                created_at, display_date, imported_at,
                source, source_id, transcribe_status, tags, summarize_status)
               VALUES (?, 'text', ?, ?, ?, ?, ?, 'cli', ?, 'not_needed', ?, ?)""",
            (
                content,
                rel_path,
                filepath.stat().st_size,
                now.isoformat(),
                display_date,
                now.isoformat(),
                source_id,
                tags_storage,
                summarize_status,
            ),
        )
        await db.commit()
        note_id = cursor.lastrowid
    finally:
        await db.close()

    return {
        "ok": True,
        "id": note_id,
        "created_at": now.isoformat(),
        "display_date": display_date,
        "source": "cli",
        "type": "text",
        "tags": tags,
        "file_path": rel_path,
        "summarize_status": summarize_status,
    }


async def list_notes(
    limit: int = 20,
    offset: int = 0,
    media_type: str | None = None,
    tag: str | None = None,
    query: str | None = None,
) -> dict[str, Any]:
    """List notes using filters suitable for scripts and agents."""
    await init_db()
    db = await get_db()
    try:
        conditions = ["n.is_deleted = 0"]
        params: list[Any] = []

        if media_type:
            conditions.append("n.media_type = ?")
            params.append(media_type)

        if tag:
            conditions.append("(n.tags LIKE ? OR n.tags LIKE ? OR n.tags = ? OR n.tags LIKE ?)")
            params.extend([f"{tag},%", f"%,{tag},%", tag, f"%,{tag}"])

        if query:
            sanitized_q = _sanitize_fts_query(query)
            if sanitized_q:
                conditions.append("n.id IN (SELECT rowid FROM notes_fts WHERE notes_fts MATCH ?)")
                params.append(sanitized_q)

        where = " AND ".join(conditions)
        cursor = await db.execute(
            f"""SELECT n.* FROM notes n
                WHERE {where}
                ORDER BY n.created_at DESC
                LIMIT ? OFFSET ?""",
            params + [limit, offset],
        )
        rows = [dict(row) for row in await cursor.fetchall()]
        return {
            "ok": True,
            "notes": [_note_summary(row) for row in rows],
            "limit": limit,
            "offset": offset,
        }
    finally:
        await db.close()


async def show_note(note_id: int) -> dict[str, Any]:
    """Return one note with full content and attachments."""
    await init_db()
    db = await get_db()
    try:
        cursor = await db.execute("SELECT * FROM notes WHERE id = ? AND is_deleted = 0", (note_id,))
        row = await cursor.fetchone()
        if not row:
            raise LookupError(f"note not found: {note_id}")

        note = dict(row)
        cursor = await db.execute(
            "SELECT * FROM attachments WHERE note_id = ? ORDER BY sort_order",
            (note_id,),
        )
        note["attachments"] = [dict(a) for a in await cursor.fetchall()]
        note["tags"] = _split_tags(note.get("tags"))
        return {"ok": True, "note": note}
    finally:
        await db.close()


async def search_notes(query: str, limit: int = 20) -> dict[str, Any]:
    """Search notes with SQLite FTS."""
    return await list_notes(limit=limit, query=query)


def read_stdin_or_arg(text: str | None, use_stdin: bool) -> str:
    if use_stdin:
        return sys.stdin.read()
    if text is None:
        raise ValueError("provide TEXT or use --stdin")
    return text
